version: 0.2

env:
  variables:
    NODE_ENV: production

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - npm ci

  pre_build:
    commands:
      - echo "Pre-build step (optional)"

  build:
    commands:
      - echo Building application and packaging artifact...
      # Create an artifact zip suitable for Elastic Beanstalk. Exclude .git and node_modules.
      - zip -r app.zip . -x "./.git/*" "node_modules/*" "*.zip" "*.7z"

artifacts:
  files:
    - app.zip

cache:
  paths:
    - node_modules/**/*
