/**
 * Test Data Configuration
 * Contains test user credentials and sample request payloads
 */

module.exports = {
  // Test Users
  users: {
    admin: {
      email: 'admin@example.com',
      password: 'admin123', // Note: Actual password hash in DB
      authority: 100,
      isSystemAdmin: true,
      expectedId: null // Will be populated from DB
    },
    coordinator: {
      email: 'patrickkurtv@gmail.com',
      password: 'coordinator123', // Note: Actual password hash in DB
      authority: 60,
      isSystemAdmin: false,
      expectedId: null // Will be populated from DB
    },
    stakeholder: {
      email: 'jpetalio@gmail.com',
      password: 'stakeholder123', // Note: Actual password hash in DB
      authority: 30,
      isSystemAdmin: false,
      expectedId: null // Will be populated from DB
    }
  },

  // Helper function to generate dates dynamically
  getDateInDays: (daysFromNow) => {
    return new Date(Date.now() + daysFromNow * 24 * 60 * 60 * 1000).toISOString();
  },

  // Sample Request Payloads
  // Note: Request_ID and Event_ID are auto-generated by the service
  // Dates are generated dynamically to ensure they're always in the future
  // CRITICAL: Date validation compares DAYS (not times), so each test needs a unique DAY
  // offsetDays: optional parameter to ensure unique DAYS per test (defaults to 0)
  // Example: Test 1 = 7 days, Test 2 = 8 days, Test 3 = 9 days (different days, not times)
  requestPayloads: {
    stakeholder: (offsetDays = 0) => {
      const baseDays = 7; // Base: 7 days from now
      const totalDays = baseDays + offsetDays; // Each test gets unique day
      const startDate = new Date(Date.now() + totalDays * 24 * 60 * 60 * 1000);
      // Set time to 10:00 AM to avoid timezone issues
      startDate.setHours(10, 0, 0, 0);
      return {
        Event_Title: 'Test Blood Drive Event',
        Event_Description: 'Automated test blood drive event',
        Date: startDate.toISOString(), // Use Date instead of Start_Date
        Location: 'Test Location',
        Email: 'test@example.com',
        Phone_Number: '+639123456789',
        Category: 'BloodDrive',
        Target_Donation: 100,
        VenueType: 'Indoor'
      };
    },
    coordinator: (offsetDays = 0) => {
      const baseDays = 10; // Base: 10 days from now
      const totalDays = baseDays + offsetDays; // Each test gets unique day
      const startDate = new Date(Date.now() + totalDays * 24 * 60 * 60 * 1000);
      // Set time to 10:00 AM to avoid timezone issues
      startDate.setHours(10, 0, 0, 0);
      return {
        Event_Title: 'Coordinator Created Event',
        Event_Description: 'Event created by coordinator for testing',
        Date: startDate.toISOString(), // Use Date instead of Start_Date
        Location: 'Coordinator Test Location',
        Email: 'coordinator@example.com',
        Phone_Number: '+639123456789',
        Category: 'BloodDrive',
        Target_Donation: 150,
        VenueType: 'Indoor'
      };
    },
    admin: (offsetDays = 0) => {
      const baseDays = 14; // Base: 14 days from now
      const totalDays = baseDays + offsetDays; // Each test gets unique day
      const startDate = new Date(Date.now() + totalDays * 24 * 60 * 60 * 1000);
      // Set time to 10:00 AM to avoid timezone issues
      startDate.setHours(10, 0, 0, 0);
      return {
        Event_Title: 'Admin Created Event',
        Event_Description: 'Event created by admin for testing',
        Date: startDate.toISOString(), // Use Date instead of Start_Date
        Location: 'Admin Test Location',
        Email: 'admin@example.com',
        Phone_Number: '+639123456789',
        Category: 'BloodDrive',
        Target_Donation: 200,
        VenueType: 'Indoor'
      };
    }
  }
};

